-- Insertar datos de los productos desde MySQL
insert into productos (nombre, categoria, precio, imagen, estrellas, descripcion) values ('Iphone 13 Pro Max', 'celulares', 80000, 'images/phone13.jpg', 3, 'Pantalla Super Retina XDR de 6.7 pulgadas con ProMotion para una sensación más rápida y sensible El modo cinematográfico añade poca profundidad de campo y cambia el enfoque automáticamente en tus videos Sistema de cámara profesional con nuevas cámaras telefoto, gran angular y ultra gran angular de 12 MP; Escáner LiDAR; Rango de zoom óptico de 6x; fotografía macro; Estilos fotográficos, video ProRes, Smart HDR 4, modo nocturno, Apple ProRAW, grabación 4K Dolby Vision HDR Cámara frontal TrueDepth de 12MP con modo nocturno, grabación 4K Dolby Vision HDR Chip Bionic A15 para un rendimiento rápido Hasta 28 horas de reproducción de vídeo, la mejor duración de la batería de un iPhone Diseño duradero con escudo de cerámica Resistencia al agua lasificación IP68 Compatible con 5 G iOS 15 incluye nuevas características para hacer más con iPhone que nunca antes.');

insert into productos (nombre, categoria, precio, imagen, estrellas, descripcion) values ('PlayStation 5', 'consolas', 52000, 'images/playstation-5-.jpg', 5, 'Consola de videojuegos de tamaño: 35cm de alto y 25 de ancho, que puede colocarse en posición vertical que termina en forma de dos aletas en la parte superior. El interior del cuerpo está iluminado con una luz azul y tiene dos joystick. Color del producto: blanco')

insert into productos (nombre, categoria, precio, imagen, estrellas, descripcion) values ('Webcam logitech', 'camaras', 9600, 'images/Webcam Ultra HD.jpg', 2, 'Cámara reflex profesional. Dimensiones: 14.3 centímetros de ancho por 11.2 centímetros de alto y 8.3 centimetros de profundidad. Peso aproximado: 760 gramos. Color del producto: negro');

insert into productos (nombre, categoria, precio, imagen, estrellas, descripcion) values ('Audifonos Razer', 'accesorios', 5800, 'images/Audifonos Razer Kraken RGB.jpg', 3, 'Para brindarle una mayor inmersión de audio, los controladores personalizados Razer de 50 mm se diseñaron y ajustaron para brindar un audio más rico que nunca. La firma de sonido única de estos impresionantes controladores produce agudos nítidos y graves retumbantes que lo pondrán en el medio de la acción. La forma óptima ha sido un enfoque integral en el diseño del Razer Kraken Pro V2. No importa cuánto duren tus sesiones de juego, te sentirás tan cómodo como un profesional Fabricada en aluminio bauxita, la nueva y mejorada diadema del Razer Kraken Pro V2 es liviana y extremadamente flexible, por lo que obtienes una mayor durabilidad sin sacrificar la comodidad. Micrófono totalmente retráctil con control remoto en línea para una comunicación nítida. Almohadillas ovaladas: diseñadas para cubrir toda la oreja, perfectas para una comodidad duradera. Sensibilidad a 1 kHz- 123 dB. Drivers con imanes de neodimio. Micrófono disponible solo en PC.');

insert into productos (nombre, categoria, precio, imagen, estrellas, descripcion) values ('Xbox series', 'consolas', 35000, 'images/Xbox series X.jpg', 5, 'Presentamos Xbox Series X, la Xbox más rápida y potente que nunca. Juega miles de títulos de las cuatro generaciones de consolas, todos los juegos se ven y juegan mejor en Xbox Series X. Experimenta velocidad y rendimiento de próxima generación con la arquitectura de velocidad Xbox, alimentada por un SSD personalizado y software integrado. Juega miles de juegos de 4 generaciones de Xbox con retro compatibilidad, incluyendo títulos optimizados al lanzar. Descarga y juega más de 100 juegos de alta calidad, incluyendo todos los nuevos títulos de Xbox Game Studios como Halo Infinite el día en que se lanzan, con Xbox Game Pass Ultimate (la membresía se vende por separado). El envío de Xbox Smart te garantiza jugar a la mejor versión disponible de tu juego sin importar en qué consola estés jugando.');

insert into productos (nombre, categoria, precio, imagen, estrellas, descripcion) values ('Notebook Asus', 'notebooks', 52999, 'images/Laptop Asus X515MA.jpg', 1, 'NVIDIA GeForce RTX 3060 6GB GDDR6 con ROG Boost hasta 1802MHz a 115W (130W con Dynamic Boost 2.0) Último procesador AMD Ryzen 9 16M (caché de 16 M, hasta 4.6 GHz) Pantalla de tipo IPS de 144 Hz y 15.6 pulgadas Full HD 1920 x 1080 16 GB DDR4 3200 MHz RAM | 512 GB PCIe SSD | Windows 10 Home Sistema térmico de refrigeración inteligente ROG con compuesto térmico de metal líquido Grizzly color del producto: negro.');

insert into productos (nombre, categoria, precio, imagen, estrellas, descripcion) values ('Notebook MSI', 'notebooks', 48000, 'images/Laptop MSI.jpg', 3, 'Potencia: el procesador Intel Core i7 de 12.ª generación ofrece la máxima eficiencia en los juegos, el trabajo multitarea y la productividad. Todo comienza ahora: disfrute de la última generación de Windows 11 Home para sus necesidades diarias. *MSI recomienda Windows 11 Pro para uso profesional. Ray-Tracing: la GPU para portátiles NVIDIA GeForce RTX 3060 con la arquitectura RTX de 2ª generación de NVIDIA para obtener los gráficos con trazado de rayos más realistas y funciones de IA de vanguardia. Pantalla fluida: la pantalla de 17,3" y 144Hz ofrece la velocidad de actualización rápida para un juego fluido y vibrante. Datos de alta velocidad: SSD Gen 4x4 y memoria DDR4-3200 para la transferencia de datos, la velocidad del sistema y la capacidad de respuesta más rápidas. Juega con frescura: con el Cooler Boost 5 más reciente utiliza 2 ventiladores y 6 tubos de calor para garantizar una óptima disipación térmica y proporcionar la mejor experiencia de juego o crear proyectos de varias capas.');

insert into productos (nombre, categoria, precio, imagen, estrellas, descripcion) values ('Audifonos Logitech', 'accesorios', 4000, 'images/Audifonos Logitech.jpg', 2, ' Diseñado para PlayStation con Tempest 3D Audio en PS5 y galardonado sonido Arctis para escuchar cada detalle y obtener la ventaja competitiva La llave USB-C multiplataforma con conexión inalámbrica de 2,4 GHz de baja latencia añade flexibilidad para intercambiar entre sistemas de forma rápida y sin problemas. (Adaptador USB-A incluido) La batería mejorada de 30 horas dura incluso tus sesiones de juego más largas y carga rápida de 15 minutos para 3 horas de uso. Soporte actualizado para el último estándar de carga USB-C Arctis 7P+ (2021) actualiza el 7P con todas las nuevas características como USB-C y batería de 30 horas de duración pero con el mismo audio impresionante - Parte de la galardonada familia Arctis 7 "PC Gamer Best Wireless Gaming Headset - Arctis 7');

insert into productos (nombre, categoria, precio, imagen, estrellas, descripcion) values ('Macbook Air', 'notebooks', 74000, 'images/MacBooK Air.jpg', 4, 'Duración de la batería durante todo el día: dura más que nunca con hasta 18 horas de duración de la batería. Potente rendimiento: enfréntate a todo, desde edición de calidad profesional hasta juegos llenos de acción con facilidad. El chip Apple M1 con una CPU de 8 núcleos ofrece un rendimiento hasta 3.5 veces más rápido que la generación anterior mientras utiliza mucho menos energía. Memoria superrápida: 8 GB de memoria unificada hace que todo tu sistema sea rápido y sensible. De esta manera puede soportar tareas como navegar con múltiples pestañas y abrir un enorme archivo gráfico de forma rápida y fácil. Impresionante pantalla: con una pantalla Retina de 13.3 pulgadas, las imágenes cobran vida con nuevos niveles de realismo. El texto es nítido y claro, y los colores son más vibrantes.');

insert into productos (nombre, categoria, precio, imagen, estrellas, descripcion) values ('Samsung Galaxy', 'celulares', 70000, 'images/samsung_galaxy.png', 3, 'Video súper estable de 8 K: Grabar videos que rivalizan con lo épica que es tu vida con una impresionante grabación 8K, la resolución de grabación más alta disponible en un smartphone; el video capturado es sin esfuerzo gracias a la estabilización de video de enfoque automático en Galaxy S22 Ultra* Fotografía nocturna + modo de portátil: Captura la noche con imágenes y videos claros y brillantes, sin importar la iluminación con el modo nocturno; el modo Retrato detecta automáticamente y se ajusta a lo que quieras frontal y central, haciendo que todas tus fotos sean dignas de un marco Resolución de fotos de 108 MP + pantalla brillante: Captura detalles premium con resolución de 108 MP: la más alta disponible en un teléfono celular; tu contenido favorito se verá aún más épico en nuestra pantalla más brillante con Vision Booster Contraste de color adaptable: Transmitiendo sobre la marcha, trabajando desde tu patio o viendo atracones hasta altas horas de la noche La pantalla adaptable Galaxy S22 Ultra optimiza automáticamente el color y el brillo, exteriores e interiores.');

insert into productos (nombre, categoria, precio, imagen, estrellas, descripcion) values ('Xbox One', 'consolas', 15000, 'images/Xbox One.jpg', 4, 'La consola está formada por un procesador AMD de 8 núcleos Custom de 64 bits basado en microarquitectura Jaguar y una velocidad estimada en 1,75 Ghz, 8 GB de memoria RAM DDR3 más 32 MB de ESRAM, con una velocidad de hasta 204 GB/s​ 500 GB de disco duro y un lector Blu-ray 6x.');

insert into productos (nombre, categoria, precio, imagen, estrellas, descripcion) values ('Mouse Gamer', 'accesorios', 3999, 'images/Mouse Gamer Xtech XTM.jpg', 5, 'Botones personalizables y memoria integrada: 11 comandos personalizados asignados a los botones y guarda hasta 5 perfiles listos para jugar directamente al ratón. Sensor de 16 K: el sensor de alto rendimiento más preciso de Logitech, con hasta 16.000 DPI para la máxima velocidad, precisión y capacidad de respuesta en todo el rango de DPI Tensión del botón del interruptor mecánico: sistema de tensión de muelles de metal y bisagras pivotantes incorporadas en los botones del ratón de juego izquierdo y derecho para una sensación nítida y limpia, con retroalimentación de clic rápido. Sistema de peso ajustable: alcance hasta cinco pesos extraíbles de 0.13 oz dentro del ratón para un ajuste personalizado del peso y el equilibrio. Iluminación RGB programable y tecnología LIGHTSYNC: personalice la iluminación de casi 16,8 millones de colores para que coincida con los colores de su equipo, dedique sus propios colores o sincronice los de otros equipos Logitech G.');
